# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

make_lazy_sexp <- function(prom) {
    .Call('lazy_make_lazy_sexp', PACKAGE = 'lazy', prom)
}

make_lazy_name_env <- function(name, env) {
    .Call('lazy_make_lazy_name_env', PACKAGE = 'lazy', name, env)
}

