# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

address <- function(x) {
    .Call('lazy_address', PACKAGE = 'lazy', x)
}

make_lazy <- function(name, env) {
    .Call('lazy_make_lazy', PACKAGE = 'lazy', name, env)
}

